export const DEFAULT_ITEM = {
  keywordLink: '',
  rank: 0,
  keyword: '',
  exposedCount: 0,
  category: '',
  keywordCategory: '',
  shoppingIndex: 0,
  informationIndex: 0,
  adUnitPriceForPc: 0,
  adUnitPriceForMobile: 0,
  searchCountOnPc: 0,
  searchCountOnMobile: 0,
  totalSearchCount: 0,
  totalProductCount: 0,
  intensity: 0,
  averageClickCount: 0,
  averageClickCountOnPc: 0,
  averageClickCountOnMobile: 0,
  clickCompetitionRate: 0,
  costPerClick: 0,
};

export const LABEL_TO_KEY: Record<string, keyof typeof DEFAULT_ITEM> = {
  '상세정보 확인': 'keywordLink',
  순위: 'rank',
  키워드: 'keyword',
  노출횟수: 'exposedCount',
  '대표 카테고리': 'category',
  '키워드 분류': 'keywordCategory',
  '쇼핑성 지수': 'shoppingIndex',
  '정보성 지수': 'informationIndex',
  'PC 광고 단가': 'adUnitPriceForPc',
  '모바일 광고 단가': 'adUnitPriceForMobile',
  'PC 검색': 'searchCountOnPc',
  '모바일 검색': 'searchCountOnMobile',
  '총 검색수': 'totalSearchCount',
  상품수: 'totalProductCount',
  경쟁강도: 'intensity',
  '평균 클릭수': 'averageClickCount',
  PC클릭률: 'averageClickCountOnPc',
  모바일클릭률: 'averageClickCountOnMobile',
  '클릭 경쟁률': 'clickCompetitionRate',
  '클릭대비 광고비': 'costPerClick',
};
